# syntax=docker/dockerfile:1
FROM python:3.8.3-alpine

ARG SKIPRUNNING

# Environmental Variables for the Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Setup of Working Directory
WORKDIR /oceansuite

# Copy the requirements.txt file
COPY requirements.txt requirements.txt

# Update apk and pip
RUN echo "**** Update apk and Pip ****" && \
    apk update && \
    pip install --upgrade pip wheel

# Install Required Dependencies
RUN echo "**** install build packages ****" && \
    apk add --no-cache --virtual=build-dependencies --upgrade \
        cairo-dev \
        freetype-dev \
        gcc \ 
        gdk-pixbuf-dev \
        gpgme-dev \
        jpeg-dev \ 
        lcms2-dev \
        libc-dev \
        libffi-dev \
        mariadb-dev \
        musl-dev \
        openjpeg-dev \
        pango-dev \
        python3-dev \
        tcl-dev \
        tiff-dev \
        tk-dev \
        zlib-dev

# Install Required Python Dependencies
RUN echo "**** install python packages ****" && \
    pip install -r requirements.txt

# Copy everything into the destination
COPY . .

RUN echo "**** See if skip running variable passed: ${SKIPRUNNING}" && \
    VAR1="${SKIPRUNNING}"; \
    VAR2="true"; \
    if [ "$VAR1" = "$VAR2" ]; \
    then echo "Skipping Running"; \
    else \
    echo "NOT SKIPPING"; \
    echo $skipRunning; \
    # echo "**** running NearBeach ****"; \
    # python manage.py wait_for_database; \
    # echo "**** running python migrate"; \
    # python manage.py migrate; \
    # echo "**** Initialise admin in NearBeach"; \
    # python manage.py initadmin; \
    # echo "**** Start NearBeach"; \
    # python manage.py runserver 0.0.0.0:8000; \
    fi  
