services:
  db:
    image: mariadb:10.5.8
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
  web:
    build: .
    working_dir: /oceansuite
    command: >
      sh -c "python manage.py wait_for_database &&
             python manage.py migrate &&
             python manage.py initadmin &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/oceansuite
    ports:
      - 8000:8000
      - 2525:2525
    env_file:
      - ./.env
    depends_on:
      - db


