version: '3'

services:
    db:
        image: mariadb:10.11
        container_name: nearbeach-db
        networks:
          - backend
        ports:
        - 3306:3306
        environment:
        - MARIADB_DATABASE=<<Please fill>>
        - MARIADB_USER=<<Please fill>>
        - MARIADB_PASSWORD=<<Please fill>>
        - MARIADB_ROOT_PASSWORD=<<Please fill>>
        volumes:
        - ./init:/docker-entrypoint-initdb.d
    nearbeach:
        image: robotichead/nearbeach:latest
        container_name: nearbeach
        networks:
          - backend
        environment:
        - SECRET_KEY=<<Please fill>>
        - SMTP_EMAIL_HOST=<<Please fill>>
        - SMTP_EMAIL_PORT=<<Please fill>>
        - SMTP_EMAIL_HOST_USER=<<Please fill>>
        - SMTP_EMAIL_HOST_PASSWORD=<<Please fill>>
        - DB_DATABASE=<<Please fill>>
        - DB_USER=<<Please fill>>
        - DB_PASSWORD=<<Please fill>>
        - DB_HOST=nearbeach-db
        - DB_ENGINE=mysql
        - DB_PORT=3306
        - ADMIN_USERNAME=<<Please fill>>
        - ADMIN_EMAIL=<<Please fill>>
        - ALLOWED_HOSTS=<<yourdomain.com.au>>
        - CSRF_TRUSTED_URLS=<<https://yourdomain.com.au>>
        - AWS_ACCESS_KEY_ID=<<Please fill>>
        - AWS_SECRET_ACCESS_KEY=<<Please fill>>
        - AWS_STORAGE_BUCKET_NAME=<<Please fill>>
        - AWS_S3_ENDPOINT_URL=<<Please fill>>
        volumes:
        - .:/ceansuite
        ports:
        - 8000:8000
        - 2525:2525
        command: >
            sh -c "python manage.py wait_for_database &&
                ls -al &&
                python manage.py migrate &&
                python manage.py initadmin &&
                python manage.py runserver 0.0.0.0:8000"
        restart: unless-stopped
        depends_on:
        - db

networks:
  backend:
