version: '3'

networks:
  # thing to note is that it seems network referenced externally is prefix by folder name
  minio-ext_backend:
    external: true

services:
  minio:
    image: 'bitnami/minio:latest'
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    networks:
      - minio-ext_backend
