name: NearBeach Base Docker Automation

on:
  schedule:
    - cron: '14 3 * * 1,3,5'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push NearBeach base
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.base
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nearbeach-base:main
