name: NearBeach Docker Automation

on:
  push:
    branches:
      - 'main'
      - 'test-nomad-builds'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/arm64,linux/amd64,linux/amd64/v2,linux/ppc64le,linux/s390x,linux/arm/v7,linux/arm/v6
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nearbeach:latest
      -
  nomad-build:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it
    - 
      name: Start the mariaDb database
      uses: getong/mariadb-action@v1.1
      with:
        # host port: 3306 # Optional, default value is 3306. The port of host
        # container port: 3307 # Optional, default value is 3306. The port of container
        # character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
        # collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
        # mariadb version: '10.4.10' # Optional, default value is "latest". The version of the MariaDB
        mysql database: 'nearbeach' # Optional, default value is "test". The specified database which will be create
        # mysql root password: ${{ secrets.RootPassword }} # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: 'nearbeach' # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: 'test12345' # Required if "mysql user" exists. The password for the "mysql user"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push nomad
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-nomad
          push: true
          build-args: SECRET_KEY=12345, MYSQL_HOST=localhost, MYSQL_DATABASE=nearbeach, MYSQL_USER=nearbeach, MYSQL_PASSWORD=test12345

          platforms: linux/arm64,linux/amd64,linux/amd64/v2,linux/ppc64le,linux/s390x,linux/arm/v7,linux/arm/v6
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nearbeach:nomad-latest
