on:
  repository_dispatch:
    types: [test_result]

jobs:
  run_if_failure:
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: ${{ github.event.client_payload.version }}
        run: echo $MESSAGE
