name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: robotichead/nearbeach
    - name: NearBeach
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
