name: NearBeach Docker Automation

on:
  repository_dispatch:
    types: [deploy_nearbeach]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nearbeach:latest
      -
        name: Build and push versioned - ${{ github.event.client_payload.version }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/arm64,linux/amd64
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/nearbeach:${{ github.event.client_payload.version }}
      -
        name: Notify Discord
        run: |
          curl -i -H "Accept: application/json" -H "Content-Type:application/json" -X POST --data "{\"content\": \"New NearBeach (${{ github.event.client_payload.version }}) release in 30 minutes. YAY <@&933378018288762901>\"}" ${{ secrets.DISCORD_WEBHOOK }}
